config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages', to: 'pages#index'
  root to: 'pages#index'
  resources :lessons, only: [:show, :index]
  resources :practices, only: [:create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checkpoint.rb
class Checkpoint < ApplicationRecord
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :programs
end

app/models/practice.rb
class Practice < ApplicationRecord
end

app/models/program.rb
class Program < ApplicationRecord
  belongs_to :lesson
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  def index
    @lessons = Lesson.order(:number).includes(:programs).all()
  end

  def show
    practices = Practice.where(user_id: current_user.id).map do |practice|
      [practice.checkpoint_id, practice]
    end
    @checked = Hash[*practices.flatten]
    @practice = Practice.new
    num = params[:id]
    render(num)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  def index
    @lessons = Lesson.order(:number).includes(:programs).all()
  end
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  before_action :authenticate_user!
  def create
    practice = Practice.new(practice_params)
    practice.user_id = current_user.id
    practice.save
    render json: practice
  end

  def practice_params
    params.require(:practice).permit(:checkpoint_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/application/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">LearnExcel</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnExcel</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <div class="container">
    <%= render partial: 'header' %>
    <% if notice || alert %>
        <div class="row" >
          <% if notice %>
              <div class="col-xs-12" >
                <p class="alert alert-success"><%= notice %></p>
              </div>
          <% end %>
          <% if alert %>
              <div class="col-xs-12" >
                <p class="alert alert-danger"><%= alert %></p>
              </div>

          <% end %>
        </div>
    <% end %>

    <%= yield %>

  </div>

  </body>
</html>

app/views/lessons/1.html.erb
<div class="lesson" >
  <div class="row">
    <div class="col-xs-12 ">
      <div class="lesson_header">
        <h1>第一章 はじめに</h1>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-10 ">
      <div class="lesson_content">
        <p>
          この章ではエクセルの基本的な使い方を学習していきます。
          <br />
          Excelとは、Microsoft社が提供している表計算ソフトウェアです。<br />
          Microsoft officeにはExcelの他にも、Word・Powerpoint・Access等のプロダクトがあり世界中で利用されています。<br />
          とても便利で様々なシーンで利用できるソフトウェアなので、マスターして仕事を効率化させましょう。<br />
          <br />
          今回はExcelの使い方について解説していきます。
        </p>


        <div id="part1" >
          <h2>エクセルを起動し、新規作成してみよう。</h2>
          windowsではエクセルはデフォルト（もともとの状態）で搭載されています。
          <br />
          起動させる場合は左下にあるwindowsマークをクリック、もしくはキーボード左下にあるwindowsマークをタイプし、エクセルを選択します。
          <br />
          （図解ホーム画面でスタートを選択した時の図）
          <br />
          シーンにしたがって、シートの種類を選択し新規作成します。（大抵の場合は、空のブックを利用します）。
          <br />
          （図解新規作成の画面）
          <br />
          この画面が表示されたらエクセルを正しく起動できています。
          <br />
          （図解からのシートが表示されている画面）
        </div>

        <div id="part2" >
          <h2>エクセルファイルを保存してみよう。</h2>
          編集したファイルの保存方法について説明します。先ほど立ち上げたファイルを利用して保存方法を学習していきましょう。
          <br />
          保存形式は大きく、「保存」と「名前をつけて保存」の２種類あります。
          <br />
          <h3>保存</h3>
          新規作成したファイルを保存する場合・一度も保存をしたことが無いファイルの場合に利用します。
          <br />
          上部のメニューバーから「ファイル」→「保存」を選択し編集したファイルを保存することができます。
          <br />
          （図解メニューバーから保存を選択するまで）
          <br />
          ここでファイルに名前をつけて保存することになります。すでに同じディレクリで利用しているファイルと同一の名前は利用することができません。
          <br />
          ここではファイル名を、「test.xlsx」と設定しデスクトップに保存しみましょう。
          <br />
          ディレクトリが異なっているとしても、同じファイル名で保存することは管理の仕方として後に問題が起きてしまう可能性があるので極力違うファイル名にしましょう。
          <br />
          次に、ファイルを保存する場所を選択します。ここではデスクトップに保存しましょう。
          <br />
          （図解保存場所を選択するもの）
          <br />
          これで正しくファイルが保存されました。デスクトップを見て確認して見ましょう。
          <br />

          <div class="well" >
            <h4>要点チェック</h4>
            <%= render partial: 'checkpoint', locals:{id: 1, text: 'デスクトップ上に、test.xlsxというファイル名で保存することができた'} %>
          </div>

          <br />

          <h3>☆ワンランクアップ</h3>
               	保存などよく使うコマンドに関してはショートカットが存在します。
          <br />
            	保存の場合は、command + sで保存することができます。
          <br />
            	ポイントはまずキーボードにある「command」を押し、そのまま「s」を押す事です。
          <br />
            	初めて保存する場合は、ファイル名等を設定するウィンドウが表示されますが、２回目以降の保存の場合は何も表示されません。
          <br />
          		「ちゃんと保存されているか心配だな」と思われるかもしれませんが、しっかりと保存されているので心配いりません。
          <br />


          <h3>名前をつけて保存</h3>
          一度保存したファイルだけども、違う名前で保存したい時に利用します。
          <br />
           上部のメニューバーから「ファイル」→「名前を付けて保存」を選択し編集したファイルを保存することができます。
          <br />
          先ほど作ったtest.xlsxを利用してtest2.xlsxという名前のファイルを作ってみましょう。
          <br />

          まずtest.xlsxを開きます。この状態で、「ファイル」→「名前を付けて保存」を選択します。
          <br />
           初めて保存する時と同じウィンドウが出てきたら、名前と保存する場所を選択します。
          <br />
           今回の場合は、以下の条件で保存してみましょう。
          <br />
           名前→test2.xlsx
          <br />
          ディレクトリ→デスクトップ

          正しく保存できましたか？ホーム画面を見て確認して見ましょう。
          <br />
          <div class="well" >
            <h4>要点チェック</h4>
            <%= render partial: 'checkpoint', locals:{id: 2, text: 'デスクトップ上に、test.xlsxに加えてtest2.xlsxというファイルを保存することができた。'} %>
          </div>
        </div>

        <div id="part3" >
          <h2>隣のシートを作成し、シート間移動する。</h2>
          エクセルでは一つのウィンドウで複数のシートを利用する事ができます。複数のシートを利用することによってファイルを複数作る事無く業務を効率化させる事ができます。
          <br />
          シートを加える場合は、下部の「＋」ボタンをクリックすることによって何枚でも追加することができます。
          <br />
          （図解）
          <br />
          シート間を移動する場合は、「Ctrl + Fn」を押しながらキーボードの↑、もしくは、↓で移動することができます。
          <br />
          <div class="well" >
            <h4>要点チェック</h4>
            <%= render partial: 'checkpoint', locals:{id: 3, text: '新たに”sheet2”を作成することができた。'} %>
            <br />
            <%= render partial: 'checkpoint', locals:{id: 4, text: 'シート間の移動がショートカットで出来た'} %>


          </div>
        </div>
        <div id="part4" >
          <h2>実際にシートにデータを記入していこう。</h2>
          test.xlsxを利用してシートにデータを記入してみましょう。
          <br />
          まずA列1行目（最上段の左隅）を選択し、F2ボタンを一回押してみましょう。F2を押すことによってダブルクリックすること無くセルを選択することができます。基本中の基本ですが、知らない人が多く便利なので使っていきましょう。
          <br />
          セルを選択した後は「id」と入力してみましょう。正しく入力できたら、エンターを入力することによって決定することができます。上記と同じ手順で、
          <br />
          <ul>
            <li>B1（B列1行目）⇒商品名</li>
            <li>C1⇒単価</li>
            <li>D1⇒発注数</li>
            <li>E1⇒合計金額</li>
          </ul>


          と入力してみましょう。
          <div class="well" >
            <h4>要点チェック</h4>
            <%= render partial: 'checkpoint', locals:{id:5 , text: '正しく、文字を入力することができた。'} %>
          </div>

          正しく入力できたでしょうか？入力ができたらカーソルをA2に持って行きましょう。
          <br />
          A2に半角で”1”と入力して下さい。続けてA3に”2”と入力します。
          <div class="well" >
            <h4>要点チェック</h4>
            <%= render partial: 'checkpoint', locals:{id: 6, text: ' それぞれ正しく数字を入力することができた。'} %>
          </div>


          A2にカーソルをあわせ、Shiftを押したままA3に移動してみてください。２つを同時に選択することができたでしょうか？同時に選択することができたら
          ポインターを右下に合わせ、そのまま下へドラッグ＆ドロップして数字を１0まで追加させてみましょう。
          <br />
          （画像）
          <br />
          次はB列に移動します。B列は「商品名」のカラムでしたね。
          <br />
          それでは下記のデータを入力してみましょう。
          <br />

          <ul>
            <li>B2⇒ペン </li>
            <li>B3⇒本 </li>
            <li>B4⇒鉛筆 </li>
            <li>B５⇒ノート </li>
            <li>B６⇒ボールペン </li>
            <li>B７⇒傘 </li>
            <li>B８⇒PC </li>
            <li>B９⇒マウス </li>
            <li>B１０⇒キーボード </li>
            <li>B１１⇒赤ペン </li>
          </ul>

          （画像）
          <div class="well" >
            <h4>要点チェック</h4>
            <%= render partial: 'checkpoint', locals:{id: 7, text: 'B列にそれぞれ正しく値を入力することができた。'} %>
          </div>


          次にC列の「単価」に移ります。それぞれ下記のデータを入力して下さい。
          <br/>
          <ul>
            <li>C2⇒100</li>
            <li>C3⇒1000</li>
            <li>C4⇒80</li>
            <li>C５⇒120</li>
            <li>C６⇒110</li>
            <li>C７⇒1500</li>
            <li>C８⇒100000</li>
            <li>C９⇒2300</li>
            <li>C１０⇒20000</li>
            <li>C１１⇒100</li>
          </ul>

          （画像）
          <div class="well" >
            <h4>要点チェック</h4>
            <%= render partial: 'checkpoint', locals:{id: 8, text: 'C列にそれぞれ正しく単価を入力することができた。'} %>
          </div>


          最後に、D列の「発注数」を入力しましょう。単純作業は最後になります。頑張っていきましょう。
          <br />
          それぞれ下記の通りにデータを入力して下さい。
          <ul>
            <li>D2⇒5</li>
            <li>D3⇒5</li>
            <li>D4⇒10</li>
            <li>D５⇒8</li>
            <li>D６⇒6</li>
            <li>D７⇒2</li>
            <li>D８⇒1</li>
            <li>D９⇒3</li>
            <li>D１０⇒1</li>
            <li>D１１⇒10</li>
          </ul>
          （画像）
          <div class="well" >
            <h4>要点チェック</h4>
            <%= render partial: 'checkpoint', locals:{id: 9, text: 'D列にそれぞれ正しく単価を入力することができた。'} %>
          </div>

          正しくデータ手動で入力することができたら次に移りましょう。
        </div>


        <div id="part5" >
          <h2>簡単な関数を使ってみよう</h2>

          さて、準備が完了しました。ここからがエクセルの面白いところになります。
          <br />
          これからE列にそれぞれの商品の「合計金額」を入力していきましょう。いちいち自分計算して数値を入力するのは時間もかかり間違えるリスクもあります。
          <br />
          そこでここでは簡単な関数を使います。コンピューターは同じ事を続ける事が得意です。
          <br />
          <br />

          まず、E２にカーソルをあわせます。作業セルを選択するのでここでF2を押します。
          <br />
          ここで使う関数は「掛け算」の関数です。まず関数を今から記入するという宣言である「=」（半角で入力して下さい）を書き始めます。
          <br />
          答えから記述すると「=C2*D2」と入力しエンターキーを一度入力すると、B2の商品の合計金額が入力されるはずです。正しく記述できたでしょうか？
          <br />
          上記と同様に、すべての商品の合計金額を関数で求めてみましょう。
          <br />
          今作業しているE2セルをコピーします。（Ctrl + c）コピーしたセルが点線で囲まれたら、うまくコピーできた証拠です。
          <br />
          それでは前回と同様にセルの右下から最後のセル（今回の場合ではE11になります）までドラッグ＆ドロップします。
          <br />
          各商品毎に異なる合計金額を計算することが出来たでしょうか？
          <br />
          <br />

          関数をうまく使う事によって作業を格段と効率化することができます。
          <br />
          他にも便利な関数があるのチェックしてみましょう。
          <br />
          <a href="https://dekiru.net/article/4429/" >https://dekiru.net/article/4429/</a>


          <div class="well" >
            <h4>要点チェック</h4>
            <%= render partial: 'checkpoint', locals:{id: 10, text: ' 関数を用いて、すべての合計金額を入力することができた。'} %>
          </div>


          <h3>☆ワンランクアップ</h3>
          ショートカットを覚えましょう。E2に記入した関数を除き、他の関数（E３-E11）を削除しましょう。
          <br />
          E3-E11を選択して、右上にあるDeleteキーを一度タイプすることで全てのデータを消す事ができます。これも便利なので覚えときましょう。
          <br />
          それでは本題に移ります。
          <br />
          コピー（Ctrl + c）までの手順は同じです。今まではマウスを使ってドラッグ＆ドロップしていた行為をキーボードで完結させましょう。範囲を選択するのは（shift + 矢印）で選択することができます。
          <br />
          <br />
          今回で言えば、「shiftを押し<strong>ながら</strong>、↓」でE11まで選択しましょう。
          <br />
          <br />
          それでは、コピーした関数を貼り付けます。貼り付けるショートカットは（Ctrl + v）です
          <br />
          コピーと貼り付けのショートカットは必要不可欠なショートカットです。しっかり使い慣れましょう。
          <br />
          <div class="well" >
            <h4>要点チェック</h4>
            <%= render partial: 'checkpoint', locals:{id: 11, text: 'コピーと貼り付けをショートカットを使って行う事ができた。'} %>

          </div>

          <br />
          以上でエクセルの基本は終了です。お疲れ様でした。

        </div>



      </div>
    </div>
    <div class="col-xs-2 " id="curriculum_side_container">
     <div class="progress_box">
        <h4>進捗度
        <i id="numerator" ></i>
        </h4>
        <div id="progress" >
          <div id="progress_bar" class="progress-bar-info">

          </div>
        </div>
     </div>
    </div>
  </div>
</div>

app/views/lessons/2.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>第２章 ショートカットを使い慣れていこう</h1>

    <div id="part1" >
      <h2>形式を選択して貼り付けてみよう</h2>
      第一章で作成したtest.xlsxを使います。まずsheet2があることを確認してください。（削除してしまった方は下部の＋ボタンを一度クリックして追加してください。）
      それでは、sheet1に書かれいる内容の一部をsheet2にコピーしてみましょう。

      まず、sheet1のE列を選択します。
      ここでデータが記入されている範囲をコピー（Ctrl + c）します。選択範囲が点線で囲まれたら正しくコピーされています。
      （図解）
      次に、sheet2へ移動しましょう。移動するときは（「Ctrl + Fn」を押しながらキーボードの↑、もしくは、↓）で移動しましょう。
      移動する事ができたら、カーソルはどこでもいいので貼り付け（Ctrl + v）をしてみましょう。

      すると、合計金額のみが正しくコピーされず「#REF!」と表示されます。
      これは、関数を計算する上で大元のデータが無いことによるエラーです。
      数値を正しくコピーするためには「形式を選択してコピー」する必要があります。
    </div>


    <div id="part2" >
      <h2>値を指定してコピーしてみよう</h2>

    </div>
  </div>
</div>

app/views/lessons/_checkpoint.erb
<%= form_for @practice do |f| %>
    <%= f.check_box :checkpoint_id, {:checked => @checked[id].present?, class: 'practice_checkpoint_id'}, id, 0 %>
    <%= text %>
<% end %>

app/views/pages/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="jumbotron">
      <h1>Excel!</h1>
      <p>...</p>
      <p><a class="btn btn-primary btn-lg" href="#" role="button">はじめる</a></p>
    </div>

  </div>
</div>

<div class="row">
  <% @lessons.each.with_index(1) do |lesson, index| %>
      <div class="col-xs-4">
        <div class="panel panel-default">
          <div class="panel-heading">第<%= lesson.number.to_s  %>章<%= lesson.name %></div>
          <ul class="list-group">
            <li class="list-group-item">
              <%= link_to lesson.number.to_s, lesson_path(lesson.id) %>

            </li>
            <% lesson.programs.each.with_index(1) do |program, index| %>
                <li class="list-group-item">
                  <%= link_to lesson.number.to_s+'-'+program.number.to_s+' '+program.name, lesson_path(lesson.id)+'#part'+program.number.to_s %>

                </li>
            <% end %>
          </ul>
        </div>

      </div>
  <% end %>

</div>